name: Update JSON files

on:
  schedule:
    - cron: "0 17 * * *"   # chạy mỗi ngày lúc 17:00 UTC = 0h VN
  workflow_dispatch:       # cho phép bạn chạy tay trong tab Actions

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ Cho phép push code

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ Dùng token của GitHub Actions

      - name: Run update script
        run: bash update.sh
